services:
  - type: web
    name: hackwesttx-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python start_fresh.py && python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn hackwesttx.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-change-this-in-production-$(date +%s)
      - key: MONGODB_ENABLED
        value: True
      - key: MONGODB_URI
        value: mongodb+srv://adminN:nSkTkOFijiEWfdsoksd@cluster0.bn7mgbx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGODB_DATABASE
        value: hackwesttx_db
      - key: MONGODB_TIMEOUT
        value: "10"
      - key: USE_MONGODB_ONLY
        value: "True"
      - key: RENDER
        value: true
      - key: ALLOWED_HOSTS
        value: hackwesttx-backend.onrender.com
      - key: CREATE_SUPERUSER
        value: "True"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@hackwesttx.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "admin123"
    healthCheckPath: /api/health/ 