services:
  - type: web
    name: hackwesttx-backend
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install psycopg2-binary==2.9.10 && pip install -r requirements.txt && python start_fresh.py && python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn hackwesttx.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-change-this-in-production-$(date +%s)
      - key: DATABASE_URL
        value: postgresql://blueprint_postures_learn_user:FOlENaCbVYqr9ZwBOE5QEkSRxkKgp8Lv@dpg-d3s34rodl3ps73d29o70-a:5432/blueprint-postures-learn
      - key: RENDER
        value: true
      - key: ALLOWED_HOSTS
        value: hackwesttx-backend.onrender.com
      - key: CREATE_SUPERUSER
        value: "True"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@hackwesttx.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "admin123"
      # Optional: MongoDB for additional data storage
      - key: MONGODB_ENABLED
        value: False
    healthCheckPath: /api/health/ 