services:
  - type: web
    name: hackwesttx-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python fix_user_model_complete.py && python manage.py collectstatic --noinput
    startCommand: gunicorn hackwesttx.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-change-this-in-production-$(date +%s)
      - key: MONGODB_ENABLED
        value: True
      - key: MONGODB_URI
        value: mongodb+srv://noahkueng1_db_user:tc2FviW6Wa5kxjEO@cluster0.bn7mgbx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGODB_USER
        value: noahkueng1_db_user
      - key: MONGODB_PASSWORD
        value: tc2FviW6Wa5kxjEO
      - key: RENDER
        value: true
      - key: ALLOWED_HOSTS
        value: hackwesttx-backend.onrender.com
      - key: CREATE_SUPERUSER
        value: "True"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@hackwesttx.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        value: "admin123"
    healthCheckPath: /api/health/ 