services:
  - type: web
    name: hackwesttx-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start_render.py
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-change-this-in-production-$(date +%s)
      - key: MONGODB_ENABLED
        value: False
      - key: RENDER
        value: true
      - key: ALLOWED_HOSTS
        value: hackwesttx-backend.onrender.com
    healthCheckPath: /api/health/
