services:
  - type: web
    name: hackwesttx-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: ./start_with_migrations.sh
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        value: django-insecure-change-this-in-production-$(date +%s)
      - key: MONGODB_ENABLED
        value: True
      - key: MONGODB_URI
        value: mongodb+srv://noahkueng1_db_user:tc2FviW6Wa5kxjEO@cluster0.bn7mgbx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGODB_USER
        value: noahkueng1_db_user
      - key: MONGODB_PASSWORD
        value: tc2FviW6Wa5kxjEO
      - key: RENDER
        value: true
      - key: ALLOWED_HOSTS
        value: hackwesttx-backend.onrender.com
    healthCheckPath: /api/health/ 