# Generated by Django 5.2.6 on 2025-09-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='extraction_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SyllabusExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(blank=True, max_length=200)),
                ('course_code', models.CharField(blank=True, max_length=20)),
                ('course_description', models.TextField(blank=True)),
                ('credits', models.IntegerField(blank=True, null=True)),
                ('prerequisites', models.TextField(blank=True)),
                ('professor_name', models.CharField(blank=True, max_length=200)),
                ('professor_email', models.EmailField(blank=True, max_length=254)),
                ('professor_office', models.CharField(blank=True, max_length=200)),
                ('professor_office_hours', models.TextField(blank=True)),
                ('professor_phone', models.CharField(blank=True, max_length=20)),
                ('class_days', models.CharField(blank=True, max_length=50)),
                ('class_time', models.CharField(blank=True, max_length=50)),
                ('class_location', models.CharField(blank=True, max_length=200)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('exam_dates', models.JSONField(blank=True, default=list)),
                ('homework_dates', models.JSONField(blank=True, default=list)),
                ('project_dates', models.JSONField(blank=True, default=list)),
                ('quiz_dates', models.JSONField(blank=True, default=list)),
                ('final_exam_date', models.DateTimeField(blank=True, null=True)),
                ('midterm_dates', models.JSONField(blank=True, default=list)),
                ('grading_scale', models.TextField(blank=True)),
                ('grade_breakdown', models.JSONField(blank=True, default=dict)),
                ('late_policy', models.TextField(blank=True)),
                ('attendance_policy', models.TextField(blank=True)),
                ('academic_integrity', models.TextField(blank=True)),
                ('disability_accommodations', models.TextField(blank=True)),
                ('course_objectives', models.TextField(blank=True)),
                ('textbook_required', models.TextField(blank=True)),
                ('textbook_recommended', models.TextField(blank=True)),
                ('course_website', models.URLField(blank=True)),
                ('additional_resources', models.TextField(blank=True)),
                ('extraction_confidence', models.FloatField(default=0.0)),
                ('extraction_method', models.CharField(default='ai_extraction', max_length=50)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('syllabus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='api.syllabus')),
            ],
        ),
    ]
