# Generated by Django 5.2.6 on 2025-09-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_syllabus_extraction_error_syllabus_extraction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classportfolio',
            name='attendance_grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Attendance grade', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='current_grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current overall grade percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='exam_grades',
            field=models.JSONField(blank=True, default=list, help_text='List of exam grades'),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='grade_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Grade breakdown by category'),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='homework_grades',
            field=models.JSONField(blank=True, default=list, help_text='List of homework grades'),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='last_grade_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='participation_grade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Participation grade', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='project_grades',
            field=models.JSONField(blank=True, default=list, help_text='List of project grades'),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='quiz_grades',
            field=models.JSONField(blank=True, default=list, help_text='List of quiz grades'),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
