# Generated by Django 5.2.6 on 2025-09-13 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_classportfolio_attendance_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes (optional)', null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_option_index',
            field=models.IntegerField(blank=True, help_text='Index of correct option (0-based)', null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation for the correct answer'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='is_true',
            field=models.BooleanField(blank=True, help_text='True if answer is True, False if answer is False', null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False')], default='multiple_choice', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('mixed', 'Mixed (Multiple Choice + True/False)')], default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='List of answer options for multiple choice'),
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('time_taken_minutes', models.IntegerField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('answers', models.JSONField(default=dict, help_text='Dictionary of question_id: user_answer')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('quiz', 'user')},
            },
        ),
    ]
