# Generated by Django 5.2.6 on 2025-09-13 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_quizquestion_correct_answer_quiz_is_published_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='processed_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('pptx', 'PowerPoint Presentation'), ('doc', 'Word Document (Legacy)'), ('ppt', 'PowerPoint (Legacy)')], max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('context', models.CharField(choices=[('lecture_notes', 'Lecture Notes'), ('syllabus', 'Syllabus'), ('assignment', 'Assignment'), ('textbook', 'Textbook Chapter'), ('presentation', 'Presentation Slides'), ('handout', 'Handout'), ('other', 'Other')], default='other', max_length=50)),
                ('extracted_text', models.TextField()),
                ('ai_summary', models.TextField(blank=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('word_count', models.IntegerField(default=0)),
                ('char_count', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processed_files', to='api.classportfolio')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
