# Generated by Django 5.2.6 on 2025-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_processedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('docx', 'Word Document'), ('pptx', 'PowerPoint Presentation'), ('doc', 'Word Document (Legacy)'), ('ppt', 'PowerPoint (Legacy)'), ('txt', 'Text Document')], max_length=10),
        ),
    ]
