# Generated by Django 5.2.6 on 2025-09-13 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_is_verified_user_profile_visibility_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classportfolio',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD for paid portfolios', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for searchability'),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public_preview', 'Public Preview'), ('public_full', 'Public Full'), ('paid', 'Paid')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='classportfolio',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('paused', 'Paused'), ('removed', 'Removed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('campus_license_available', models.BooleanField(default=False)),
                ('campus_license_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listing', to='api.classportfolio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promo_code_used', models.CharField(blank=True, max_length=50, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(default='stripe', max_length=50)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.marketplacelisting')),
            ],
            options={
                'ordering': ['-purchased_at'],
                'unique_together': {('listing', 'buyer')},
            },
        ),
        migrations.AddField(
            model_name='marketplacelisting',
            name='buyers',
            field=models.ManyToManyField(related_name='purchased_portfolios', through='api.PortfolioPurchase', to=settings.AUTH_USER_MODEL),
        ),
    ]
