# Generated by Django 5.2.6 on 2025-09-14 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_classportfolio_collaborators_classportfolio_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classportfolio',
            unique_together={('professor', 'semester', 'year')},
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
