# Generated by Django 5.2.6 on 2025-09-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_classportfolio_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classportfolio',
            name='attendance_grade',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='collaborators',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='current_grade',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='exam_grades',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='grade_breakdown',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='homework_grades',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='last_grade_update',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='participation_grade',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='price',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='project_grades',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='quiz_grades',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='classportfolio',
            name='visibility',
        ),
        migrations.AlterField(
            model_name='classportfolio',
            name='professor',
            field=models.CharField(max_length=100),
        ),
    ]
