# Generated by Django 5.2.6 on 2025-09-14 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_classportfolio_attendance_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(help_text='Unique file identifier', max_length=100, unique=True)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('download_url', models.URLField(help_text='S3 download URL')),
                ('bucket', models.CharField(help_text='S3 bucket name', max_length=100)),
                ('folder', models.CharField(help_text='S3 folder path', max_length=100)),
                ('learn_method', models.CharField(choices=[('summary', 'Summary'), ('extract', 'Extract'), ('analyze', 'Analyze')], default='summary', help_text='Learning method applied to the document', max_length=50)),
                ('learning_result', models.JSONField(default=dict, help_text='Results from document processing')),
                ('key_points', models.JSONField(default=list, help_text='Key points extracted from the document')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether document has been processed')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(blank=True, help_text='Associated portfolio (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.classportfolio')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the document', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
