# Generated by Django 5.2.6 on 2025-09-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='classportfolio',
            name='course',
            field=models.CharField(blank=True, help_text='Course name or code', max_length=100),
        ),
        migrations.AddField(
            model_name='classportfolio',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in USD', max_digits=10),
        ),
    ]
