# Generated by Django 5.2.6 on 2025-09-14 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_classportfolio_course_classportfolio_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Original filename of the document', max_length=255)),
                ('topic', models.CharField(help_text='Quiz topic', max_length=200)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('text_length', models.PositiveIntegerField(default=0, help_text='Length of source text')),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Word count of source text')),
                ('questions', models.JSONField(default=list, help_text='List of quiz questions with options and answers')),
                ('metadata', models.JSONField(default=dict, help_text='Additional quiz metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Quiz',
                'verbose_name_plural': 'Document Quizzes',
                'ordering': ['-created_at'],
            },
        ),
    ]
