# Generated by Django 5.2.6 on 2025-09-14 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_documentquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentquiz',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='documentquiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='documentquiz',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_quizzes', to='api.document'),
        ),
        migrations.AddField(
            model_name='documentquiz',
            name='quiz_data',
            field=models.JSONField(default=dict, help_text='Complete quiz data including questions and answers'),
        ),
        migrations.AlterField(
            model_name='documentquiz',
            name='text_length',
            field=models.IntegerField(help_text='Length of the source text'),
        ),
        migrations.AlterField(
            model_name='documentquiz',
            name='topic',
            field=models.CharField(help_text='Quiz topic/subject', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentquiz',
            name='total_questions',
            field=models.IntegerField(help_text='Total number of questions in the quiz'),
        ),
        migrations.AlterField(
            model_name='documentquiz',
            name='word_count',
            field=models.IntegerField(help_text='Word count of the source text'),
        ),
    ]
