# Generated by Django 5.2.6 on 2025-09-14 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_documentquiz_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='YouTube video URL', max_length=500)),
                ('title', models.CharField(blank=True, help_text='Video title (optional)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Video description (optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'YouTube Video',
                'verbose_name_plural': 'YouTube Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
