# Generated by Django 5.2.6 on 2025-10-16 20:34

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_youtubevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Learning Link', 'verbose_name_plural': 'Learning Links'},
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='description',
            field=models.TextField(blank=True, help_text='Resource description (optional)'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(blank=True, help_text='Resource title (optional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='url',
            field=models.URLField(help_text='Learning resource URL (YouTube, Coursera, articles, etc.)', max_length=500, validators=[api.models.validate_safe_url]),
        ),
    ]
