# Generated by Django 5.2.6 on 2025-10-17 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_update_youtubevideo_to_learning_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Event description (optional)')),
                ('event_type', models.CharField(choices=[('homework', 'Homework'), ('test', 'Test'), ('exam', 'Exam'), ('quiz', 'Quiz'), ('project', 'Project'), ('presentation', 'Presentation'), ('lab', 'Lab'), ('reading', 'Reading'), ('study_session', 'Study Session'), ('office_hours', 'Office Hours'), ('review_session', 'Review Session'), ('other', 'Other')], default='other', help_text='Type of event', max_length=20)),
                ('due_date', models.DateTimeField(help_text='Due date/time for the event')),
                ('reminder_time', models.DateTimeField(blank=True, help_text='Optional: Time to send reminder', null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('cancelled', 'Cancelled')], default='not_started', help_text='Current status', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level', max_length=10)),
                ('points', models.IntegerField(blank=True, help_text='Points/grade weight (optional)', null=True)),
                ('location', models.CharField(blank=True, help_text='Location of event (optional)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the event was completed', null=True)),
                ('class_portfolio', models.ForeignKey(blank=True, help_text='Optional: Link to a specific class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='api.classportfolio')),
                ('linked_resources', models.ManyToManyField(blank=True, help_text='Learning resources linked to this event', related_name='calendar_events', to='api.youtubevideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Calendar Event',
                'verbose_name_plural': 'Calendar Events',
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['user', 'due_date'], name='api_calenda_user_id_36bd65_idx'), models.Index(fields=['event_type', 'due_date'], name='api_calenda_event_t_fbb33e_idx')],
            },
        ),
    ]
