# Generated by Django 5.2.6 on 2025-10-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='classportfolio',
            name='color',
            field=models.CharField(default='#6366F1', help_text='Hex color code for visual identification (e.g., #FF5733)', max_length=7),
        ),
    ]
